/*
 * StacksData API
 * Stacksdata provides various information about Stacks blockchain through REST API. The data is as real-time as it appears on Stacks node. Finalized blocks, transactions and corresponding events are visible once the consensus is reached. This document describes what information is available and how to query it to produce various reports and dashboards.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@stacksdata.info
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.stacksonchain.controllers;

import com.stacksonchain.model.Dataset;
import com.stacksonchain.model.RunSqlRequest;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for SqlApi
 */
@Ignore
public class SqlApiTest {

    private final SqlApi api = new SqlApi();

    /**
     * 
     *
     * Executes a provided SQL. See SQL API guide for details. https://stacksdata.info/sql.html
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void runSqlTest() throws Exception {
        String body = null;
        Dataset response = api.runSql(body);

        // TODO: test validations
    }
    /**
     * 
     *
     * Executes a provided SQL. See SQL API guide for details https://stacksdata.info/sql.html.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void runSqlV2Test() throws Exception {
        RunSqlRequest body = null;
        Dataset response = api.runSqlV2(body);

        // TODO: test validations
    }
}
